set nu
set relativenumber
map tt <C-W>w
map - <C-W><
map = <C-W>>
let mapleader = " "

"===== [ make 81st column stand out ] ===========
"Courtsey Damain Conway : https://www.youtube.com/watch?v=aHm36-na4-4
highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)


" Functions to mark tasks complete and incomplete
function! MarkIncomplete()
	normal! 0f[lR 
endfunction
nnoremap <leader>xx :call MarkIncomplete()<cr>
function! MarkComplete()
	normal! 0f[lRx
endfunction
nnoremap <leader>x :call MarkComplete()<cr>


"============== [ ALE ] ==================

let g:ale_set_loclist 		     = 0
let g:ale_set_quickfix		     = 1
let g:ale_set_signs		     = 0
let g:ale_linters = {'python' : ['flake8']}
let g:airline#extensions#ale#enabled = 1

"============== [ vim-plug ] ==================
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
Plug 'JuliaEditorSupport/julia-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'christoomey/vim-tmux-navigator'
Plug 'dense-analysis/ale'
call plug#end()

syntax off
